### ISSUE TITLE
Add calendar entries as a list

### ISSUE THREAD

**Issue by mapelpapel** [fsi-hska/iwi-website#61]
Add calendar entries as a list, so that you quickly have an overview of the next events. I think it is best to place it to the right of the current calendar.

**Comment by SimonKienzler** [comment]
@mapelpapel how do you see this being implemented? The area on the right side of the calendar is intentionally left empty, so that events can be displayed when the user selects a date that has events. Would you be fine with the solution that a list of upcoming events is only displayed if the user selected a date that has no events?

**Comment by mapelpapel** [comment]
Isn't there still space on the right side of the calendar, even if an event is selected? I mean we could also do it like you said, but I think it would be better to be able to see the list all the time. I also remember from Beta-phase, that there can be pictures embedded in an event. Is this still a thing, and where are they displayed? Maybe we also need to keep an eye on that.
